### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ghost** [helloitu/PS4API-5.05#1]
that ptrace offset is wrong as it causes peoples ps4 to crash and shutdown

https://github.com/ExodusSecurity/PS4API_5.0x_Server/issues/1

**Comment by ghost** [comment]
My PS4 doesn't crash. It can't attach but notifys are working. Same problem then others "ports" made by people who doesn't even test their work.

**Comment by ghost** [comment]
Just wait for @Bisoon official port.

**Comment by Fr0st3h** [comment]
why post on github if it doesnt work?

**Comment by bgcomrade** [comment]
what do this program. can it make ps4 server so all jailbreak can put server in ps4 and everybody can play multplayer.

**Comment by Biorn1950** [comment]
@SirKob you get notification, with this one? and yes BISOON just upgraded his PS4 to 5.05
@CMTFrostyy learn about github and comeback with another comment. TY
@bgcomrade it's to enable access to real time memory

**Comment by helloitu** [comment]
I didn't execute get push, so sorry, haha, this fully worked on my Ps4 CUH-2015A

**Comment by helloitu** [comment]
@SirKob  if u are so sad with people's trying update a great job, and fixing issues as well, learn C, and ps4 calls in cturt git and code yourself, by your comment its clear that u did not even try to read any part of the code.

@Biorn1950  ty for help, im back now from school, haha <3

@CMTFrostyy  haha

@ExodusSecurity  ty for help
